modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "the_lords_land"
version = "${version}"
displayName = "The Lords Land"
authors = "samuelh2005"
description = '''
A government mod with voting, land control, and economy control
'''
#logoFile = ""

[[dependencies.the_lords_land]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.the_lords_land]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.the_lords_land]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "the_lords_land.mixins.json"
